# Generated by Django 5.2.15 on 2026-07-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentSupportDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("amount", models.PositiveIntegerField()),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor Appointment"),
                    ("body_checkup", "Body Checkup"),
                    ("blood_donation", "Blood Donation"),
                    ("organ_donation", "Organ Donation Counselling"),
                ],
                default="doctor",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="available_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="available_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="api.department",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="api.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time_slot",
            field=models.TimeField(),
        ),
    ]
